name: Testing to build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build