name: Deployment-2

on:
  workflow_run:
    workflows: 
      - Deployment-1
    types:
      - completed

jobs:
  deploy-2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for 120 seconds
        run: sleep 120
      - name: Call kb-dash-prod-2 endpoint
        run: |
          curl -X POST http://restart.kanpaibook.com/update/kb-dash-prod-2 -H "API-Key: ${{ secrets.WEBHOOK_API_KEY}}"
