name: Discord Notification Dev

on:
  workflow_run:
    workflows: 
      - Deployment-Dev
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Discord Webhook for Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "New Development Version deployed on dev-dash.kanpaibook.com",
              "url": "https://dev-dash.kanpaibook.com",
              "description": "[Changes]('$COMMIT_LINK')",
              "fields": [
                { "name": "Version", "value": "'$PACKAGE_VERSION'", "inline": false }
              ],
              "color": 16753920
            }]
          }'