# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create Development Version

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile.dev
     
          
      - name: Restart Dev Node
        run: |
          curl -X POST https://restart.kanpaibook.com/update/kb-api-dev -H "API-Key: ${{ secrets.WEBHOOK_API_KEY }}"

          

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1


      - name: Discord Webhook for Dev
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "New Development Version deployed on dev-api.kanpaibook.com",
              "url": "https://dev-api.kanpaibook.com",
              "description": "[Changes]('$COMMIT_LINK')",
              "fields": [
                { "name": "Version", "value": "'$PACKAGE_VERSION'", "inline": false }
              ],
              "color": 16753920
            }]
          }'